ENV                   = "dev" 

#MYSQL Values
MYSQL_STORAGE         =  10
MYSQL_ENGINE_VERSION  = "5.7"
MYSQL_INSTANCE_TYPE   = "db.t3.micro"

#DocDB Values
DOCDB_INSTANCE_TYPE   = "db.t3.medium"
DOCDB_INSTANCE_COUNT  = 1
DOCDB_INSTANCE_PORT   = 27017

#Redis values
REDIS_ENGINE_VERSION ="6.x"
REDIS_PORT           = 6379
REDIS_INSTANCE_TYPE  = "cache.t3.small"
REDIS_INSTANCE_COUNT = 1

# RABBITMQ Variables
RABBITMQ_PORT_NUMBER    = 5672
RABBITMQ_INSTANCE_TYPE  = "t3.micro"